export const Change_Login = 'changeLogin'
export const Save_Username = 'saveUsername'
export const Save_Nickname = 'saveNickname'
export const Change_Lesson_Info = 'changeLessonInfo'
export const Save_Question = 'saveQuestion'
export const Save_Answer = 'saveAnswer'
export const Save_Tea_Info = 'saveTeaInfo'